server:
  port: 8030
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/

#  servlet:
#    context-path: /service_client
logging:
  level:
    org.springframework.cloud.gateway: trace
    com.netfix: info
spring:
  application:
    name: admin-gateway
  cloud:
    gateway:
      discovery:
        locator:
          #是否与服务注册于发现组件进行结合，通过 serviceId 转发到具体的服务实例。默认为false，设为true便开启通过服务中心的自动根据 serviceId 创建路由的功能。
          enabled: false
      routes:
        - id: admin-core
        #目标服务地址
          uri: lb://admin-core
          order: 0
        #路由条件
          predicates:
            - Path=/admin/**
          filtes:
            - StripPrefix=1
            - AddResponseHeader=X-Response-Default-Foo, Default-Bar
            #- RewritePath=/admin/(?<segment>.*),/$\{segment}
  #          filters:
 #           - name: Hystrix
 #             args:
 #               name: fallbackcmd
 #               fallbackUri: forward:/fallback