server:
  port: 8030
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/

#  servlet:
#    context-path: /service_client
logging:
  level:
    org.springframework.cloud.gateway: debug
    com.netfix: info
spring:
  application:
    name: admin-gateway
  cloud:
    gateway:
      routes:
      - id: admin-core
        #跳转路径
        uri: lb://admin-core
        order: 0
        #路由匹配规则
        predicates:
        - Path=/admin-core/{segment}
        filters:
        #前缀去除层级
        - StripPrefix=1
        #断路器
        - name: Hystrix
          args:
            name: fallbackcmd
            fallbackUri: forward:/fallback
      default-filters:
        - Elapsed=true
    discovery:
      locator:
          #是否与服务注册于发现组件进行结合，通过 serviceId 转发到具体的服务实例。默认为false，设为true便开启通过服务中心的自动根据 serviceId 创建路由的功能。
        enabled: false
