
server:
  port: 8021
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/
  instance:
    #告诉Eureka服务端，如果我2s之内没有给你发心跳，就代表我“死”了，将我踢出掉。
    lease-expiration-duration-in-seconds: 10
    # 每间隔1s，向Eureka服务端发送一次心跳，证明自己依然”存活“。
    lease-renewal-interval-in-seconds: 5
#  servlet:
#    context-path: /service_client
logging:
  level:
    com.netfix: info
spring:
  application:
    name: admin-core
  redis:
    database: 0
    #password: Utour!-LTA-TEST
    #cluster:#集群
     # max-redirects: 3
     # nodes:
      #  - 172.16.2.191:6379
    lettuce:
      pool:
        max-active:  100 # 连接池最大连接数（使用负值表示没有限制）
        max-idle: 100 # 连接池中的最大空闲连接
        min-idle: 50 # 连接池中的最小空闲连接
        max-wait: 6000 # 连接池最大阻塞等待时间（使用负值表示没有限制）
    timeout: 1000
    host: localhost
    port: 6379
