
server:
  port: 8020
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/

#  servlet:
#    context-path: /service_client
logging:
  level:
    com.netfix: info
spring:
  application:
    name: admin-core